In [1]:
# Quero entender o que aconteceu com os exames que não achou nada e se a saida do associacao está compativel com os achados de odontograma.

In [3]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [5]:

# Definir caminhos
odontograma_path <- "/var/home/aninha/Desktop/Doutorado/Dados/dentes_predictions_all.csv"
associacao_path <- "/var/home/aninha/Desktop/Doutorado/Dados/anotadas/results.csv"

# Ler os arquivos
odontograma <- read_csv(odontograma_path)
associacao <- read_csv(associacao_path)

Rows: 63087 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): box, filename
dbl (2): score, class_name

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 105610 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): achado, imagem
dbl  (2): dente, VERSAO_PAPIRON
date (1): data_predicao

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [6]:
head(odontograma)

  box
1 [0.3332689952922059, 0.2375958624340239, 0.4972122374742745, 0.30142484203217523]
2 [0.36406188237077414, 0.26761479226369705, 0.5479083984771514, 0.32179842052005586]
3 [0.3601342288249317, 0.30850151606968473, 0.5628664664485875, 0.3593323319677323]
4 [0.3705112884707629, 0.34640228805087864, 0.5738484897317095, 0.3862503411277892]
5 [0.36680896454714834, 0.37162894805272423, 0.5810872930734553, 0.4113924826894488]
6 [0.3571137233094417, 0.3959860930367122, 0.5903175986386875, 0.43413118124008176]
  score     class_name filename
1 0.8204448 18         ALP.026080-pan_c000_panoramica.jpg
2 0.8562502 17         ALP.026080-pan_c000_panoramica.jpg
3 0.8744037 16         ALP.026080-pan_c000_panoramica.jpg
4 0.8501301 15         ALP.026080-pan_c000_panoramica.jpg
5 0.8501484 14         ALP.026080-pan_c000_panoramica.jpg
6 0.8182108 13         ALP.026080-pan_c000_panoramica.jpg

In [7]:
head(associacao)

  dente achado      imagem                             VERSAO_PAPIRON
1 11    higido      ALP.026080-pan_c000_panoramica.jpg 3.1
2 12    higido      ALP.026080-pan_c000_panoramica.jpg 3.1
3 13    higido      ALP.026080-pan_c000_panoramica.jpg 3.1
4 14    higido      ALP.026080-pan_c000_panoramica.jpg 3.1
5 15    higido      ALP.026080-pan_c000_panoramica.jpg 3.1
6 16    restauracao ALP.026080-pan_c000_panoramica.jpg 3.1
  data_predicao
1 2025-10-22
2 2025-10-22
3 2025-10-22
4 2025-10-22
5 2025-10-22
6 2025-10-22